name: Simple CI/CD for Spring Boot

on:
  push:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Build project with Maven
        run: mvn clean install

      - name: Upload build artifact
        uses: actions/upload-artifact@v2.3.1
        with:
          name: spring-boot-jar
          path: target/*.jar